[project]
name = "fault-tolerance-attacker"
version = "0.1.0"
description = ""
authors = [
    {name = "Nick Montana",email = "59708036+nick-montana@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

[project.scripts]
fault-tolerance-attacker = "main:main"

[tool.poetry]
packages = [{ include = "main.py" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
